const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];const money=n=>new Intl.NumberFormat('zh-TW',{style:'currency',currency:'TWD',maximumFractionDigits:0}).format(Number(n||0));const today=()=>new Date().toISOString().slice(0,10);const uid=p=>`${p}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,6)}`;
const DB_NAME='wiseshop-os',DB_VERSION=1,STORE='kv';let db,state;const channel='BroadcastChannel'in window?new BroadcastChannel('wiseshop-sync'):null;
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>{db=r.result;resolve(db)};r.onerror=()=>reject(r.error)})}
function idbGet(k){return new Promise((resolve,reject)=>{const r=db.transaction(STORE,'readonly').objectStore(STORE).get(k);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function idbSet(k,v){return new Promise((resolve,reject)=>{const r=db.transaction(STORE,'readwrite').objectStore(STORE).put(v,k);r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error)})}
function seed(){return{version:1,settings:{shopName:'石岡日常商店',district:'臺中市石岡區',lowStockThreshold:8},orders:[],inventory:[{id:'P1',sku:'SG-JAM-001',name:'石岡柑橘果醬',stock:6,reorder:10,cost:130,price:260,sold7:11,leadDays:4},{id:'P2',sku:'COF-DRIP-010',name:'手沖咖啡包',stock:23,reorder:12,cost:75,price:190,sold7:16,leadDays:3},{id:'P3',sku:'BOX-LOCAL-01',name:'地方選物禮盒',stock:4,reorder:6,cost:680,price:1280,sold7:5,leadDays:5}],customers:[],expenses:[],automations:[],tasks:[],aiHistory:[],events:[]}}
async function save(reason){state.events=state.events||[];state.events.unshift({id:uid('EV'),time:new Date().toISOString(),reason});state.events=state.events.slice(0,80);await idbSet('state',state);channel?.postMessage({type:'state-updated'});$('#saveState').textContent='● 本機已儲存';render()}
function toast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),2200)}
function pending(){return(state.orders||[]).filter(o=>!['已完成','已取消'].includes(o.status))}function lowStock(){return(state.inventory||[]).filter(p=>Number(p.stock)<=Number(p.reorder))}function revenue(){return(state.orders||[]).filter(o=>o.date===today()&&o.status!=='已取消').reduce((s,o)=>s+Number(o.amount||0),0)}
function recommended(p){const avg=Number(p.sold7||0)/7;return Math.max(0,Math.ceil(avg*(Number(p.leadDays||3)+5)*1.2-Number(p.stock||0)))}
function aiFocus(){const low=lowStock(),p=pending();if(low.length&&p.length)return`先完成 ${p.length} 筆待處理訂單；${low.map(x=>x.name).slice(0,2).join('、')} 已到補貨線。`;if(low.length)return`${low.map(x=>x.name).slice(0,2).join('、')} 庫存偏低，建議今天安排補貨。`;if(p.length)return`目前有 ${p.length} 筆訂單尚未完成，先處理出貨／製作即可。`;return'目前沒有急迫異常。可以查看 VIP 回訪或確認明日備貨。'}
function render(){state.orders=state.orders||[];state.inventory=state.inventory||[];state.customers=state.customers||[];state.expenses=state.expenses||[];state.tasks=state.tasks||[];state.events=state.events||[];$('#shopName').textContent=state.settings?.shopName||'我的店家';$('#todayRevenue').textContent=money(revenue());$('#pendingCount').textContent=pending().length;$('#lowStockCount').textContent=lowStock().length;$('#focusText').textContent=aiFocus();renderOrders();renderTasks();renderStock();renderActivity()}
function renderOrders(){const list=$('#orderList'),rows=(state.orders||[]).filter(o=>o.date===today()).sort((a,b)=>String(b.id).localeCompare(String(a.id))).slice(0,8);if(!rows.length){list.innerHTML='<div class="empty">今天還沒有訂單，按「快速開單」開始</div>';return}list.innerHTML=rows.map(o=>`<div class="list-item"><div class="list-main"><strong>${escapeHtml(o.customer||'現場顧客')} · ${money(o.amount)}</strong><small>${o.channel||'門市'} · ${o.id}</small></div><div class="list-actions"><span class="status ${o.status==='已完成'?'':'warn'}">${o.status||'待處理'}</span>${!['已完成','已取消'].includes(o.status)?`<button class="mini-button" data-complete="${o.id}">完成</button>`:''}</div></div>`).join('');$$('[data-complete]',list).forEach(b=>b.onclick=()=>completeOrder(b.dataset.complete))}
function renderTasks(){const list=$('#taskList'),rows=(state.tasks||[]).slice(0,8);if(!rows.length){list.innerHTML='<div class="empty">今天沒有待辦事項</div>';return}list.innerHTML=rows.map(t=>`<label class="list-item task-item ${t.done?'task-done':''}"><input class="task-check" type="checkbox" data-task="${t.id}" ${t.done?'checked':''}><div class="list-main"><strong>${escapeHtml(t.text)}</strong><small>${t.done?'已完成':'待處理'}</small></div></label>`).join('');$$('[data-task]',list).forEach(c=>c.onchange=async()=>{const t=state.tasks.find(x=>x.id===c.dataset.task);if(t){t.done=c.checked;await save(`${c.checked?'完成':'恢復'}待辦：${t.text}`)}})}
function renderStock(){const list=$('#stockList'),rows=[...state.inventory].sort((a,b)=>(a.stock/a.reorder)-(b.stock/b.reorder)).slice(0,6);if(!rows.length){list.innerHTML='<div class="empty">尚未建立商品</div>';return}list.innerHTML=rows.map(p=>{const ratio=Math.min(100,Math.max(4,Number(p.stock)/(Number(p.reorder)||1)*60)),cls=p.stock<=p.reorder*.5?'critical':p.stock<=p.reorder?'low':'';return`<div class="stock-card ${cls}"><strong>${escapeHtml(p.name)}</strong><small>${escapeHtml(p.sku||'')} · 現有 ${p.stock}</small><div class="stock-bar"><i style="width:${ratio}%"></i></div><small>${p.stock<=p.reorder?`建議補 ${recommended(p)} 件`:'庫存正常'}</small></div>`}).join('')}
function renderActivity(){const list=$('#activityList'),rows=(state.events||[]).slice(0,7);if(!rows.length){list.innerHTML='<div class="empty">操作紀錄會顯示在這裡</div>';return}list.innerHTML=rows.map(e=>`<div class="activity"><span class="activity-dot"></span><div><p>${escapeHtml(e.reason||'更新資料')}</p><time>${formatTime(e.time)}</time></div></div>`).join('')}
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function formatTime(v){if(!v)return'';const d=new Date(v);return new Intl.DateTimeFormat('zh-TW',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(d)}
function openModal(title,eyebrow,html){$('#modalTitle').textContent=title;$('#modalEyebrow').textContent=eyebrow;$('#modalBody').innerHTML=html;$('#modal').showModal()}
function closeModal(){if($('#modal').open)$('#modal').close()}
function newOrder(){const opts=state.inventory.map(p=>`<option value="${p.id}">${escapeHtml(p.name)}｜${money(p.price)}｜庫存 ${p.stock}</option>`).join('');openModal('快速開單','新增訂單',`<div class="form-grid"><div class="field full"><label>顧客姓名</label><input id="oCustomer" placeholder="現場顧客／姓名" autocomplete="off"></div><div class="field"><label>來源</label><select id="oChannel"><option>門市</option><option>LINE</option><option>IG</option><option>電話</option><option>其他</option></select></div><div class="field"><label>狀態</label><select id="oStatus"><option>待處理</option><option>製作中</option><option>待出貨</option><option>已完成</option></select></div><div class="field full"><label>商品（選填，會同步扣庫存）</label><select id="oProduct"><option value="">不指定商品</option>${opts}</select></div><div class="field"><label>數量</label><input id="oQty" type="number" min="1" value="1"></div><div class="field"><label>金額</label><input id="oAmount" type="number" min="0" placeholder="訂單總額"></div></div><div class="submit-row"><button value="cancel" class="cancel-button">取消</button><button type="button" id="saveOrder" class="submit-button">建立訂單</button></div>`);const product=$('#oProduct'),qty=$('#oQty'),amount=$('#oAmount');const updateAmount=()=>{const p=state.inventory.find(x=>x.id===product.value);if(p)amount.value=Number(p.price||0)*Math.max(1,Number(qty.value||1))};product.onchange=updateAmount;qty.oninput=updateAmount;$('#saveOrder').onclick=async()=>{const customer=$('#oCustomer').value.trim()||'現場顧客',q=Math.max(1,Number(qty.value||1)),p=state.inventory.find(x=>x.id===product.value),a=Number(amount.value||0);if(!a){toast('請填寫訂單金額');return}const id=`O-${String(Date.now()).slice(-6)}`;state.orders.unshift({id,date:today(),customer,channel:$('#oChannel').value,amount:a,status:$('#oStatus').value});if(p){p.stock=Math.max(0,Number(p.stock)-q);p.sold7=Number(p.sold7||0)+q}upsertCustomer(customer,a);closeModal();await save(`建立訂單 ${id}｜${customer}｜${money(a)}`);toast('訂單已建立')}}
function upsertCustomer(name,amount){if(name==='現場顧客')return;let c=state.customers.find(x=>x.name===name);if(c){c.visits=Number(c.visits||0)+1;c.spent=Number(c.spent||0)+Number(amount||0);c.last=today();if(c.spent>=6000)c.tag='VIP';else if(c.visits>=3)c.tag='常客'}else state.customers.unshift({id:uid('C'),name,phone:'',visits:1,spent:Number(amount||0),last:today(),tag:'新客'})}
async function completeOrder(id){const o=state.orders.find(x=>x.id===id);if(!o)return;o.status='已完成';await save(`完成訂單 ${id}`);toast('訂單已完成')}
function checkout(){const rows=pending();openModal('快速結帳','待處理訂單',rows.length?`<div class="choice-list">${rows.map(o=>`<div class="choice-item"><div><strong>${escapeHtml(o.customer||'現場顧客')} · ${money(o.amount)}</strong><div class="eyebrow">${o.id} · ${o.channel||'門市'} · ${o.status}</div></div><button type="button" class="mini-button" data-checkout="${o.id}">完成</button></div>`).join('')}</div>`:'<div class="empty">目前沒有待處理訂單</div>');$$('[data-checkout]',$('#modalBody')).forEach(b=>b.onclick=async()=>{await completeOrder(b.dataset.checkout);checkout()})}
function inventory(){const opts=state.inventory.map(p=>`<option value="${p.id}">${escapeHtml(p.name)}｜目前 ${p.stock}</option>`).join('');openModal('庫存調整','進貨／售出／盤點',`<div class="form-grid"><div class="field full"><label>商品</label><select id="iProduct">${opts}</select></div><div class="field"><label>動作</label><select id="iMode"><option value="add">進貨增加</option><option value="sub">售出／耗用</option><option value="set">盤點設定</option></select></div><div class="field"><label>數量</label><input id="iQty" type="number" min="0" value="1"></div></div><div class="submit-row"><button value="cancel" class="cancel-button">取消</button><button type="button" id="saveInventory" class="submit-button">儲存調整</button></div>`);$('#saveInventory').onclick=async()=>{const p=state.inventory.find(x=>x.id===$('#iProduct').value),q=Math.max(0,Number($('#iQty').value||0)),mode=$('#iMode').value;if(!p)return;const before=Number(p.stock||0);if(mode==='add')p.stock=before+q;if(mode==='sub')p.stock=Math.max(0,before-q);if(mode==='set')p.stock=q;closeModal();await save(`庫存調整：${p.name} ${before} → ${p.stock}`);toast('庫存已更新')}}
function customer(){openModal('顧客查詢','CRM 快速搜尋',`<div class="field"><label>輸入姓名或電話</label><input id="customerQuery" placeholder="例如：林小姐" autocomplete="off"></div><div id="customerResults"></div>`);const input=$('#customerQuery'),box=$('#customerResults');const draw=()=>{const q=input.value.trim().toLowerCase();const rows=state.customers.filter(c=>!q||`${c.name} ${c.phone||''}`.toLowerCase().includes(q)).slice(0,8);box.innerHTML=rows.length?rows.map(c=>`<div class="customer-result"><strong>${escapeHtml(c.name)}</strong><div class="customer-meta"><span class="chip">${escapeHtml(c.tag||'顧客')}</span><span class="chip">來店 ${c.visits||0} 次</span><span class="chip">累計 ${money(c.spent)}</span><span class="chip">最近 ${c.last||'—'}</span></div></div>`).join(''):'<div class="empty">找不到顧客</div>'};input.oninput=draw;draw();setTimeout(()=>input.focus(),50)}
function task(){openModal('新增待辦','交班與工作提醒',`<div class="field"><label>待辦內容</label><input id="taskText" placeholder="例如：下午 3 點前聯絡供應商" autocomplete="off"></div><div class="submit-row"><button value="cancel" class="cancel-button">取消</button><button type="button" id="saveTask" class="submit-button">加入待辦</button></div>`);$('#saveTask').onclick=async()=>{const text=$('#taskText').value.trim();if(!text){toast('請輸入待辦內容');return}state.tasks.unshift({id:uid('T'),text,done:false});closeModal();await save(`新增待辦：${text}`);toast('待辦已加入')}}
function expense(){openModal('快速記帳','店家支出',`<div class="form-grid"><div class="field full"><label>項目</label><input id="eName" placeholder="例如：包材補貨"></div><div class="field"><label>分類</label><select id="eCategory"><option>進貨</option><option>耗材</option><option>行銷</option><option>運費</option><option>其他</option></select></div><div class="field"><label>金額</label><input id="eAmount" type="number" min="0" placeholder="0"></div></div><div class="submit-row"><button value="cancel" class="cancel-button">取消</button><button type="button" id="saveExpense" class="submit-button">儲存支出</button></div>`);$('#saveExpense').onclick=async()=>{const name=$('#eName').value.trim(),amount=Number($('#eAmount').value||0);if(!name||!amount){toast('請填寫項目與金額');return}state.expenses.unshift({id:uid('E'),date:today(),name,category:$('#eCategory').value,amount});closeModal();await save(`記錄支出：${name} ${money(amount)}`);toast('支出已記錄')}}
function bind(){document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;({"new-order":newOrder,checkout,inventory,customer,task,expense}[b.dataset.action]||(()=>{}))()});$('#runCheckBtn').onclick=()=>{render();toast('已重新分析今日營運')};$('#notifyBtn').onclick=async()=>{if(!('Notification'in window)){toast('此裝置不支援通知');return}const p=await Notification.requestPermission();toast(p==='granted'?'提醒已開啟':'未開啟通知權限')};channel?.addEventListener('message',async e=>{if(e.data?.type==='state-updated'){state=await idbGet('state')||state;render()}});document.addEventListener('visibilitychange',async()=>{if(!document.hidden&&db){state=await idbGet('state')||state;render()}})}
async function init(){try{await openDB();state=await idbGet('state')||seed();await idbSet('state',state)}catch(err){console.warn(err);state=seed();toast('目前使用暫存模式')};bind();render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(console.warn)}init();
